#!/usr/bin/sh

arg1=$1
arg2=$2

if [[ $arg1 = '' ]]; then
    docker-compose up -d
fi

if [[ $arg1 = 'logs' ]]; then
    if [[ $arg2 != '' ]]; then
        docker-compose logs -ft $arg2
    else 
        docker-compose logs -ft
    fi
fi

if [[ $arg1 = 'stop' ]]; then
    docker-compose down
fi
